using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Text;

namespace NetP3DLib.Generators;

[Generator]
public class ChunkGenerator : IIncrementalGenerator
{
    private const string ChunkAttributesFullName = "NetP3DLib.P3D.Attributes.ChunkAttributes";
    private const string EndianAwareBinaryReaderFullName = "NetP3DLib.IO.EndianAwareBinaryReader";

    private static readonly DiagnosticDescriptor MissingConstructor = new("P3D001", "Chunk missing required constructor", "Chunk '{0}' must define a constructor (EndianAwareBinaryReader) or (EndianAwareBinaryReader, uint)", "NetP3DLib.Generators", DiagnosticSeverity.Error, true);

    private static readonly DiagnosticDescriptor DuplicateIdentifier = new("P3D002", "Duplicate chunk identifier", "Chunk identifier '{0}' is used by both '{1}' and '{2}'", "NetP3DLib.Generators", DiagnosticSeverity.Error, true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var chunkClasses = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                ChunkAttributesFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetChunkData(ctx))
            .Where(static data => data is not null);

        context.RegisterSourceOutput(context.CompilationProvider.Combine(chunkClasses.Collect()), static (spc, source) => Execute(spc, source.Right));
    }

    private static ChunkData? GetChunkData(GeneratorAttributeSyntaxContext context)
    {
        var symbol = (INamedTypeSymbol)context.TargetSymbol;
        var attribute = context.Attributes.First(a => a.AttributeClass?.ToDisplayString() == ChunkAttributesFullName);

        if (attribute.ConstructorArguments.Length == 0 || attribute.ConstructorArguments[0].Value is not uint id)
            return null;

        bool hasReaderCtor = false;
        bool hasHeaderCtor = false;

        foreach (var ctor in symbol.InstanceConstructors)
        {
            var parameters = ctor.Parameters;

            if (parameters.Length == 1 && parameters[0].Type.ToDisplayString() == EndianAwareBinaryReaderFullName)
                hasReaderCtor = true;

            if (parameters.Length == 2 && parameters[0].Type.ToDisplayString() == EndianAwareBinaryReaderFullName && parameters[1].Type.SpecialType == SpecialType.System_UInt32)
                hasHeaderCtor = true;
        }

        return new ChunkData(symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), id, hasHeaderCtor, hasReaderCtor, symbol.Locations.FirstOrDefault());
    }

    private static void Execute(SourceProductionContext context, System.Collections.Immutable.ImmutableArray<ChunkData?> chunks)
    {
        if (chunks.IsDefaultOrEmpty)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.IO;");
        sb.AppendLine();
        sb.AppendLine("namespace NetP3DLib.P3D");
        sb.AppendLine("{");
        sb.AppendLine("    public static partial class ChunkLoader");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>Registers internal chunks found at compile-time.</summary>");
        sb.AppendLine("        private static void LoadInternalChunks()");
        sb.AppendLine("        {");

        var seenIdentifiers = new Dictionary<uint, ChunkData>();

        foreach (var chunk in chunks.Where(c => c != null))
        {
            var c = chunk!;

            if (!c.HasReaderCtor && !c.HasHeaderCtor)
            {
                context.ReportDiagnostic(Diagnostic.Create(MissingConstructor, c.Location, c.FullyQualifiedName));
                continue;
            }

            if (seenIdentifiers.TryGetValue(c.Identifier, out var existing))
            {
                context.ReportDiagnostic(Diagnostic.Create(DuplicateIdentifier, c.Location, c.Identifier, existing.FullyQualifiedName, c.FullyQualifiedName));
                continue;
            }

            seenIdentifiers[c.Identifier] = c;

            if (c.HasHeaderCtor)
                sb.AppendLine($"            ChunkTypes[{c.Identifier}] = (typeof({c.FullyQualifiedName}), (br, headerSize) => new {c.FullyQualifiedName}(br, headerSize));");
            else
                sb.AppendLine($"            ChunkTypes[{c.Identifier}] = (typeof({c.FullyQualifiedName}), (br, _) => new {c.FullyQualifiedName}(br));");

            sb.AppendLine($"            ChunkTypeMap[typeof({c.FullyQualifiedName})] = {c!.Identifier};");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("ChunkLoader.g.cs", sb.ToString());
    }

    private record ChunkData(string FullyQualifiedName, uint Identifier, bool HasHeaderCtor, bool HasReaderCtor, Location? Location);
}