using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Text;

namespace NetP3DLib.Generators;

[Generator]
public class ChunkGenerator : IIncrementalGenerator
{
    private const string ChunkAttributesFullName = "NetP3DLib.P3D.Attributes.ChunkAttributes";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var chunkClasses = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                ChunkAttributesFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetChunkData(ctx))
            .Where(static data => data is not null);

        context.RegisterSourceOutput(context.CompilationProvider.Combine(chunkClasses.Collect()), static (spc, source) => Execute(spc, source.Right));
    }

    private static ChunkData? GetChunkData(GeneratorAttributeSyntaxContext context)
    {
        var symbol = (INamedTypeSymbol)context.TargetSymbol;
        var attribute = context.Attributes.First(a => a.AttributeClass?.ToDisplayString() == ChunkAttributesFullName);

        // Assuming the ID is the first constructor argument of the attribute
        if (attribute.ConstructorArguments.Length == 0 || attribute.ConstructorArguments[0].Value is not uint id)
            return null;

        return new ChunkData(
            FullyQualifiedName: symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            Identifier: id
        );
    }

    private static void Execute(SourceProductionContext context, System.Collections.Immutable.ImmutableArray<ChunkData?> chunks)
    {
        if (chunks.IsDefaultOrEmpty) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.IO;");
        sb.AppendLine();
        sb.AppendLine("namespace NetP3DLib.P3D");
        sb.AppendLine("{");
        sb.AppendLine("    public static partial class ChunkLoader");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>Registers internal chunks found at compile-time.</summary>");
        sb.AppendLine("        private static void LoadInternalChunks()");
        sb.AppendLine("        {");

        foreach (var chunk in chunks.Where(c => c != null))
        {
            // Instead of using Reflection and Expressions, we just write the exact code needed!
            sb.AppendLine($"            ChunkTypes[{chunk!.Identifier}] = (typeof({chunk.FullyQualifiedName}), br => new {chunk.FullyQualifiedName}(br));");
            sb.AppendLine($"            ChunkTypeMap[typeof({chunk.FullyQualifiedName})] = {chunk!.Identifier};");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("ChunkLoader.g.cs", sb.ToString());
    }

    private record ChunkData(string FullyQualifiedName, uint Identifier);
}